# Generated by Django 4.1.7 on 2023-09-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waph',
            name='wphrase',
            field=models.TextField(max_length=1000),
        ),
    ]
