# Generated by Django 4.1.7 on 2023-09-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_waph_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='mywallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/%y')),
                ('logoname', models.CharField(max_length=100)),
            ],
        ),
    ]
