# Generated by Django 4.1.7 on 2023-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mywallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywallets',
            name='logodetails',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
