# Generated by Django 4.1.7 on 2023-09-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_mywallets_logodetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='waph',
            name='mywallets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.mywallets'),
            preserve_default=False,
        ),
    ]
