# Generated by Django 4.1.7 on 2023-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_waph_mywallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='wafund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cimg', models.ImageField(upload_to='cimg/%y')),
                ('cinfo', models.TextField(max_length=2000)),
                ('caddress', models.CharField(max_length=100)),
            ],
        ),
    ]
