# Generated by Django 4.1.7 on 2023-09-26 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_wafund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wafund',
            new_name='coins',
        ),
    ]
