# Generated by Django 4.1.7 on 2023-09-26 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_remove_coins_cinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='wafund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coins')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
