# Generated by Django 4.1.7 on 2023-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wafund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wafund',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
