# Generated by Django 4.1.7 on 2023-09-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_wafund_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wafund',
            old_name='con',
            new_name='coins',
        ),
    ]
