# Generated by Django 4.1.7 on 2023-09-29 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_remove_wafund_amount_walletfund'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='walletfund',
            new_name='walletbalance',
        ),
    ]
