# Generated by Django 4.1.7 on 2023-09-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
