# Generated by Django 4.1.7 on 2023-09-29 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_balance_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='wafund',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
