# Generated by Django 4.1.7 on 2023-10-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='coins',
        ),
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
