# Generated by Django 4.1.7 on 2023-10-02 23:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0024_remove_fund_coins_fund_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fund',
            new_name='deposit',
        ),
    ]
