# Generated by Django 4.1.7 on 2023-10-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_fund_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='coins',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='waddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
