# Generated by Django 4.1.7 on 2023-10-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='caddress',
        ),
    ]
