# Generated by Django 4.1.7 on 2023-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_coins_caddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='waddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
