# Generated by Django 4.1.7 on 2023-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bitcoin_waddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='walletaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(max_length=100)),
                ('eth', models.CharField(max_length=100)),
                ('xrp', models.CharField(max_length=100)),
                ('xlm', models.CharField(max_length=100)),
                ('trc20', models.CharField(max_length=100)),
                ('tron', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bitcoin',
            name='waddress',
        ),
    ]
