# Generated by Django 4.1.7 on 2023-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_delete_walletaddress_bitcoin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='caddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
