# Generated by Django 4.1.7 on 2023-10-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_cbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbackup',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='coins',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ucoins',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
