# Generated by Django 4.1.7 on 2023-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_cname_backuptransaction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='cardnumber',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='expiration',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='name',
            new_name='homeandblock',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='securitycode',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='limit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='pincode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
