# Generated by Django 4.1.7 on 2023-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='buycoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos/%y')),
                ('link', models.URLField(max_length=100)),
            ],
        ),
    ]
